spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Students
    username: postgres
    password: 2104
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG